#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>

# blackbox directory
DIR="$HOME/.blackbox"

# rofi sudo askpass helper
export SUDO_ASKPASS="$DIR"/scripts/rofi_askpass

# execute the application
sudo -A $1
