#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## Autostart Programs

# blackbox dir
bbdir="$HOME/.blackbox"

# Kill already running process
_ps=(xsettingsd ksuperkey)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -9 ${_prs}
	fi
done

# Enable Simple X hotkey daemon
sxhkd -c "$bbdir"/sxhkdrc &

# Lauch xsettingsd daemon
xsettingsd --config="$bbdir"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Enable power management
xfce4-power-manager &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
hsetroot -cover "$bbdir"/theme/wallpaper

# Lauch notification daemon
"$bbdir"/scripts/bb_dunst

# Lauch polybar
"$bbdir"/scripts/bb_bar

# Lauch compositor
"$bbdir"/scripts/bb_comp

# Start mpd
exec mpd &

# Start blackbox window manager
/usr/bin/blackbox
